### PR TITLE
Change getKey to use productOrderNumber

### PR DESCRIPTION
**Pull request by jdewell**

### CODE REVIEW

**Comment by tmaness** [comment]
Looks good to me.

**Comment by matthewbjorge** [comment]
Your changes look good, though I made a refactoring example for the surrounding code - just a couple of quick changes to simplify date formatting and remove duplicated code.

[Temporary branch for example](https://github.com/hci-gnomex/gnomex/compare/mbjorge--refactoringexample)

**Comment by jdewell** [comment]
Looks like a good refactor. I'll need to do some testing. I'm sure you did some already. :)

**Comment by matthewbjorge** [comment]
I didn't do any testing at all actually. My branch was just an easier way for me to explain a refactoring opportunity than making a long-winded comment explaining what I was thinking.  :)

**Comment by jdewell** [comment]
key is of form:
2016-20160914-84
2016-20160914-84-upload_staging
where 84 in this case is the productOrderNumbere

**Comment by matthewbjorge** [comment]
Oh well I am dumb - I made two mistakes in my haste. You've probably figured them out, but:

[another diff](https://github.com/hci-gnomex/gnomex/commit/ac3dbe85b3bf49ddc28df57c359038631c9a8713)

**Comment by jdewell** [comment]
Removed backslashes from ProductOrderDownloadList which was causing problems with viewURL.
Refactored model ProductOrder to have getKey use SimpleDateFormat.

**Comment by tcourdy** [comment]
Looks good to me.  Nice refactoring suggestion Matt.

**Pull request merged**
