### PR TITLE
GNOM-2128 Uploaded files in upload_staging are not shown in the left pane of Manage Files popup.

### PR DESCRIPTION
**Pull request by jdewell**

### CODE REVIEW

**Comment by tmaness** [comment]
This looks pretty good.  Does it work?

**Comment by jdewell** [comment]
Updated this pull request with all the files needed for analysis and product order

**Comment by tmaness** [comment]
Tricky issue!  Look's good to me.

**Comment by tcourdy** [comment]
this looks good to me as well.  I will merge it.

**Pull request merged**
