### PR TITLE
gnom-2119  Fix issues with multiplex grouping when changing sequencing protocol

### PR DESCRIPTION
**Pull request by tcourdy**
https://ri-jira.hci.utah.edu/browse/GNOM-2119

### CODE REVIEW

**Comment by matthewbjorge** [comment]
Here is a simplified diff of the pull request:
image

**Comment by matthewbjorge** [comment]
As for the pull request itself, it looks good to me.

**Comment by jdewell** [comment]
Looks good.

**Comment by tmaness** [comment]
Looks good.

**Pull request merged**
