### PR TITLE
When moving a directory from the upload_staging an exception is thrown

### PR DESCRIPTION
**Pull request by jdewell**

### CODE REVIEW

**Comment by tmaness** [comment]
Looks good.

**Comment by tcourdy** [comment]
Looks good and the few tests I've done on it seem to be working correctly.  I will merge this and then update bio-dev so we can all test on the new code.

**Comment by jdewell** [comment]
Can you hold off for a few minutes? I forgot product orders again.

-John

**Comment by tcourdy** [comment]
I already merged and closed this.  You will have to create a new branch.

**Pull request merged**
