### PR TITLE
Missed a few closeSessions and remove a couple too many

### PR DESCRIPTION
**Pull request by tmaness**
My script that removed hibernate closeSession missed a few routines and should not have removed them in routines that extend HttpServlet.  Also replaced gnomex_db_audit.sql with the new one.

This should be the last of the changes for 5.36!

### CODE REVIEW

**Comment by tcourdy** [comment]
We really need to standardize our coding styles across our development environments so viewing diffs won't be as cumbersome.

**Comment by jdewell** [comment]
Yes, I hear that. Unfortunately Intellij seems to format automatically sometimes. I was discussing this with Matt and I mentioned that in Eclipse you can create a standardized format file that everyone uses. I’m sure that Intellij has something similar.

-John

**Comment by tmaness** [comment]
In switching to Intellij so in the future it shouldn’t be a problem…

**Comment by tcourdy** [comment]
I believe we could come up with a standard settings file and then each of us could import that into our intelliJ.  If you go to ~/.IntelliJIdeav.xxx/config/codestyles/  You will see a .xml file of your current code styles in Intellij (This is if you have created a different profile other than the default settings.  Also the xxx would be your version number and yes there is  . at the beginning of that folder).

Anyways we could come up with styles that we agree upon on one machine and then have each of us import it into our IntelliJ's

**Comment by jdewell** [comment]
Sounds great. Just in time for our code style meeting tomorrow.

**Pull request merged**
